config/routes.rb
SlMobileMech::Application.routes.draw do
  resources :reviews

  get "admin/index"
  get "admin", to: "admin#index"

  get "home/about"
  get "home/contact"
  get "home/index"
  get "home/reviews"
  get "home/services"

  resources :appointments

  namespace :admin do
    resources :appointments
  end

  root to: 'home#index'

  

end

app/models/appointment.rb
# class EmailValidator < ActiveModel::EachValidator
#   def validate_each(record, attribute, value)
#     unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
#       record.errors[attribute] << " is not a valid email"
#     end
#   end
# end

class Appointment < ActiveRecord::Base
  validates :email, :name, :phone, :time, :reason, presence: true
  # validates :email, presence: true, email: true

  def first_name
    @first_name = name.split(' ')[0]
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  after_initialize :default_values

  private
    def default_values
      self.name ||= 'Anonymous'
    end
end

app/controllers/admin/appointments_controller.rb
class Admin::AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: ENV['username'], 
                           password: ENV['password'], only: [:index]

  # GET /admin/appointments
  # GET /admin/appointments.json
  def index
    case params[:show]
    when 'all'
      @appointments = Appointment.order("time DESC")
    when 'current'
      @appointments = Appointment.where("time > ?", Date.today).order("time ASC")
    when 'past'
      @appointments = Appointment.where("time < ?", Date.today).order("time DESC")
    else
      @appointments = Appointment.where("time > ?", Date.today).order("time ASC")
      # @appointments = Appointment.where("name LIKE ?", "%#{params[:search]}%").order("time DESC")
    end
  end

  # GET /admin/appointments/1
  # GET /admin/appointments/1.json
  def show
  end

  # GET /admin/appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /admin/appointments/1/edit
  def edit
  end

  # POST /admin/appointments
  # POST /admin/appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to admin_appointment_path(@appointment), notice: 'Appointment was successfully created.' }
        format.json { render action: 'show', status: :created, location: admin_appointment_path }
      else
        format.html { render action: 'new' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/appointments/1
  # PATCH/PUT /admin/appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to admin_appointment_path, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/appointments/1
  # DELETE /admin/appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to admin_appointments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:name, :phone, :email, :time, :reason)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  # http_basic_authenticate_with name: 'scott', password: 'bym2JSt95Hl1', only: [:index]
  http_basic_authenticate_with name: ENV['username'], 
                           password: ENV['password'], only: [:index]

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  def confirm
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        UserMailer.welcome_email(@appointment).deliver
        AdminMailer.app_notification_email(@appointment).deliver
        flash[:notice] = "Appointment created!"
        format.html { redirect_to root_path, notice: 'Appointment successfully created. An email has been sent with confirmation info. Thanks!' }
        format.json { render action: 'confirm', status: :created, location: root_path}
      else
        format.html { render action: 'new' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:name, :phone, :email, :time, :reason)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "static_page"

  def about
  end

  def contact
  end

  def index
  end

  def reviews
    @reviews = Review.order("created_at DESC")
  end

  def services
    @service_pics = Dir.glob("app/assets/images/parts/thumbnails/*.png").map do |f|
      File.basename f
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  http_basic_authenticate_with name: ENV['username'], 
                           password: ENV['password'], except: ["new", "create"]

  before_action :set_review, only: [:show, :edit, :update, :destroy]
  layout 'static_page', except: [:show, :new, :edit, :create, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.order("created_at DESC")
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        AdminMailer.review_notification_email(@review).deliver
        format.html { redirect_to root_path, notice: 'Review was successfully created. Thanks for your feedback!' }
        format.json { render action: 'show', status: :created, location: root_path }
      else
        format.html { render action: 'new' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:name, :text)
    end
end

app/helpers/admin/appointments_helper.rb
module Admin::AppointmentsHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/appointments/_form.html.erb
<%= form_for [:admin, @appointment] do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation" class="appointment errors">
      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="appointment form-wrap">
    <div class="appointment form">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="appointment form">
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </div>
    <div class="appointment form">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="appointment form">
      <%= f.label :time %><br>
      <%= f.datetime_select :time, ampm: true %>
    </div>
    <div class="appointment form">
      <%= f.label :reason %><br>
      <%= f.text_field :reason %>
    </div>
    <div class="appointment form">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/admin/appointments/_info.html.erb
<div class="appointment info">
  <p><b>Name:</b> <%= a.name %></p>
  <p><b>Email:</b> <%= a.email %></p>
  <p><b>Phone:</b> <%= a.phone %></p>
  <p><b>Time:</b> <%= a.time %></p>
  <p><b>Reason:</b> <%= a.reason %></p>
</div>

app/views/admin/appointments/edit.html.erb
<div id="wrapper">
  <h1>Edit this appointment</h1>

  <%= render 'form' %>
</div>

app/views/admin/appointments/email.html.erb
<h1>Appointment Saved</h1>
<p>A confirmation email has been sent.</p>
<%= link_to "Back to Home", root_path %>

app/views/admin/appointments/index.html.erb
<div id="appointment-wrapper">
  <div id="side-pane" class="appointment">
    <h1>Appointments</h1>
    <h2>Actions</h2>
    <ul>
      <li><%= link_to "Create an Appointment", new_admin_appointment_path %></li>
    </ul>

    <h2>Display</h2>
    <ul>
      <li><%= link_to "All Appointments", :show => 'all' %></li>
      <li><%= link_to "Current Appointments", :show => 'current' %></li>
      <li><%= link_to "Past Appointments", :show => 'past' %></li>
    </ul>

    <h2>Search</h2>
    <%= form_tag admin_appointments_path, method: "get" do %>
      <%= text_field_tag :search, params[:search] %>
      <br /> <br />
      <%# <%= submit_tag "Search", name: nil %>
    <% end %>
  </div>

  <div id="appointment-pane">
    <% if @appointments.empty? %>
      <p>No appointments matched this criteria.</p>
    <% end %>

    <% @appointments.each do |a| %>
      <div class="appointment-container <%= a.name %>">
        <%= render 'info', :a => a %>

        <div class="appointment extra-info">
          <ul>
            <li><%= link_to "Edit #{a.first_name}'s Appointment", edit_admin_appointment_path(a)%></li>
            <li><%= link_to "Delete #{a.first_name}'s Appointment", admin_appointment_path(a),
                             method: :delete, data: {confirm: "You sure you want to delete this?"} %></li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/appointments/new.html.erb
<div id="wrapper">
  <h1>Schedule an appointment</h1>

  <%= render 'form' %>
</div>

app/views/admin/appointments/show.html.erb
<h1>Here's your appointment!</h1>
<%= render 'info', :a => @appointment %><br />
<%= link_to "Edit this appointment", edit_admin_appointment_path %><br>
<%= link_to "Back to Appointments", admin_appointments_path %>

app/views/admin/index.html.erb
<div id="main-content">
  <div class="main-item shadowed">
    <h1>Admin Page</h1>
    <p>From here, you can manage the site. Users without the login info do not have access to this page.</p>

    <ul>
      <li> <%= link_to "View and Manage Appointments", admin_appointments_path %> </li>
      <li> <%= link_to "View and Manage Reviews", reviews_path %> </li>
      <li> <%= link_to "Create New Front Page Posting -- (Not yet implemented)" %> </li>
      <li> <%= link_to "Create New Special Deal Posting -- (Not yet implemented)" %> </li>
    <ul>
  </div>

  <div class="main-item shadowed">
    <h1>Don't give anyone untrusted the credentials to this page.</h1>
  </div>
</div>

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation" class="appointment errors">
      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="appointment form-wrap">
    <div class="appointment form">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="appointment form">
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </div>
    <div class="appointment form">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="appointment form">
      <%= f.label :time %><br>
      <%= f.datetime_select :time, ampm: true %>
    </div>
    <div class="appointment form">
      <%= f.label :reason %><br>
      <%= f.text_field :reason %>
    </div>
    <div class="appointment form">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/appointments/confirm.html.erb
<h1>Confirmed!</h1>
<p>An email has been sent! (Not functional yet)</p>

app/views/appointments/edit.html.erb
<div id="wrapper">
  <h1>Edit this appointment</h1>

  <%= render 'form' %>
</div>

app/views/appointments/email.html.erb
<h1>Appointment Saved</h1>
<p>A confirmation email has been sent.</p>
<%= link_to "Back to Home", root_path %>

app/views/appointments/new.html.erb
<div id="wrapper">
  <h1>Schedule an appointment</h1>

  <%= render 'form' %>
</div>

app/views/appointments/show.html.erb
<h1>Viewing Appointment</h1>
<%= render 'info', :a => @appointment %><br />
<%= link_to "Edit this appointment", edit_appointment_path %><br>
<%= link_to "Back to Home", root_path %>

app/views/home/_footer.html.erb
<footer>
  <div id="contact-info" class="footer-item">
    <h1>Contact Information</h1>
    <p>Scott Laverdiere</p>
    <p>Phone: 443-462-6178</p>
    <p>Email: <a href="mailto:slmobilemechanic@yahoo.com">slmobilemechanic@yahoo.com</a></p>
    <p>Hours: 10:00AM - 6:00PM</p>
  </div>

  <div id="business_card" class="footer-item">
    <%= image_tag "business/card.jpg" %>
  </div>

</footer>

app/views/home/_header.html.erb
<header>
  <h1><%= link_to "SL Mobile Mechanic", root_url, class: "header_main" %></h1>
  <nav>
    <ul>
      <li><%= link_to 'About', '/home/about', class: "header_sub"%></li>
      <li><%= link_to 'Services', '/home/services', class: "header_sub" %></li>
      <li><%= link_to 'Reviews', '/home/reviews', class: "header_sub" %></li>
      <li><%= link_to 'Contact', '/home/contact', class: "header_sub" %></li>
    </ul>
  </nav>
</header>

app/views/home/about.html.erb
<%# <%  TODO Add ASE Cert Picures. %>

<div class="main-item shadowed">
  <h1>Why am I a Mobile Mechanic?</h1>

  <p>
  My name is Scott, and I love fixing cars, and working outdoors. I have
  worked at dealers and independent repair shops most of my life, and for the
  most part, I really liked it. Most of the repairs I did, however, did not
  require the services only available in a shop.  In fact, probably 80% or
  more could have been repaired remotely, or didn't even require a tow.  I
  was sent by my employers constantly out to diagnose, or fix the cars of
  customers or the dealer. I began to think I should just target that area
  of business, it was challenging and fun, and saved the customer (or the
  dealer) time and money. Thats when decided to start my mobile mechanic
  business.
  </p>
  
  <p>
  I am ASE Certified, A former MD State Inspector (I would still be one, but
  you have to have a physical location to do inspections), and have 13 years
  experience.
  </p>
  
  <p>
  I can do almost any repair to any make of car, and if I don't feel that I
  am comfortable fixing your problem I will let you know and explain exactly
  why, but I haven't had that happen yet.
  </p>
</div>

<div class="main-item shadowed">
  <h1>What Services do I offer?</h1>
  <p>If you want to know specifically what services I offer, check out my <%= link_to 'services', '/home/services' %> page.
</div>

app/views/home/contact.html.erb
<div class="main-item shadowed">
  <h1>Contact Me</h1>

  <h2>Business info</h2>
  <p>If you want to make an appointment, text or call me at the number below, or
    shoot me an email.</p>

  <p><b>Phone: </b>443-462-6178</p>
  <p><b>Email: </b><a href="mailto:slmobilemechanic@yahoo.com">slmobilemechanic@yahoo.com</a></p>
</div>

<div class="main-item shadowed">
  <h2>Website info</h2>
  <p>If you find a problem with the website itself:</p>
  <p><b>Email: </b><a href="mailto:cmlaverdiere@gmail.com">cmlaverdiere@gmail.com</a></p>
</div>

app/views/home/index.html.erb
<div class="main-item shadowed">
  <h1>Welcome to SL Mobile Mechanic!</h1>
  <%= image_tag "business/van_red.jpg" %>
</div>

<div id="manifesto" class="main-item shadowed">
  <p>You're sitting in the waiting room at a repair shop, wondering how much
  it's going to cost to fix your car. Any minute now, a shop employee's going to
  slap you with the bill, along with annoying financing and credit card offers.
  We've all been there.</p>

  <p>Who can help you avoid this mess? That's who I am. I've been fixing
  all makes of cars for over 13 years, am <em>ASE certified</em>, and a
  former <em>MD state inspector.</em></p>

  <p>After years working at dealer and repair shops, I saw a need for
  quality mobile service, not just jump-starts and lockouts. I started my
  business to cultivate my love of fixing cars, and match it with my love
  of helping people through good customer relationships. </p>

  <p>I'm Scott Laverdiere, your mobile mechanic!</p>
</div>

app/views/home/reviews.html.erb
<div class="main-item shadowed">
  <h1>Customer Reviews</h1>
</div>

<% if @reviews.empty? %>
<div class="main-item shadowed">
  <p>There are currently no reviews posted. Check back later.</p>
</div>
<% end %>

<% @reviews.each do |review| %>
<div class="main-item shadowed">
  <figure>
    <figcaption>
      <%= review.name %> says...
    </figcaption>

    <blockquote>
      <q><i><%= review.text %></i></q>
    </blockquote>

  </figure>
</div>
<% end %>

<!-- <br> -->
<%# <%= link_to 'New Review', new_review_path %>

app/views/home/services.html.erb
<%# <%  TODO I should make a services controller so Scott can add new ones. %>
<%# <%  TODO Add Paypal Picures. %>

<div class="main-item shadowed">
  <h1>Services</h1>

  <p>Below are some examples of common services I provide.</p>

  <div class="images-inline">
  <% @service_pics.each do |pic| %>
    <figure class="images-inline">
      <figcaption>
        <center>
          <b><%= File.basename(pic, ".png").gsub('_', ' ') %></b>
        </center>
      </figcaption>
      <%= image_tag "parts/thumbnails/#{pic}" %>
    </figure>
  <% end %>
  </div>
</div>

<div class="main-item shadowed">
  <h1>Getting a Quote</h1>

  <p>
  To get an exact quote, call (443-462-6178) or e-mail
  slmobilemechanic@yahoo.com.
  </p>

  <p>
  Have ready your vehicle's <b>year</b>, <b>make</b>, <b>model</b>, and
  if possible the <b>VIN number</b>.
  </p>

  <p>
  Let me know what you need done, or if you need
  diagnostic work. I keep my phone on me and will receive your email instantly.
  </p>
</div>

<div class="main-item shadowed">
  <h1>Important Info</h1>
  <p>
  I will beat <b>any shop's</b> legitimate quote on a service I provide <i>(Example: I
    cannot do alignments)</i>.  I reserve the right to verify all repair quotes.
  </p>

  <p>
  I will do most estimates absolutely free, provided it doesnt involve
  diagnostic.  If im just checking engine codes, most of the time there is no
  charge.
  </p>

  <p>
  I offer regular service and diagnostics, along with emergency service (Call me
  before you call a tow truck).
  </p>

  <p>
  My hourly rate (Using Alldata's billable flat rate hours for labor) is $60 per
  flat rate hour (Your average shop charges $90/hr, plus they jack up the part
  prices for your bill, shop fees, etc.).  Of course this varies from job to job,
  and is not always what is in the book, it might be less or more depending on
  the complexity of a job.  I will give you a fair estimate based upon my
  experience, and I stand behind my work.
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SlMobileMech</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'home/header' %>

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

  <%= yield %>

  <%= render 'home/footer' %>
</body>

</html>

app/views/layouts/static_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SlMobileMech</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'home/header' %>

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

  <div id="wrapper">
    <div id="main-content">
      <%= yield %>
    </div>

    <div id="sidebar">
      <div id="make_appointment" class="sidebar-item shadowed">
        <h2>Make an Appointment</h2>
        <div id="btn-div" class="centered">
          <%= button_to "Schedule Appointment", new_appointment_path, method: :get, class: "btn fade" %>
        </div>
      </div>

      <div id="ase_cert" class="sidebar-item shadowed">
        <%= image_tag "misc/ASE_cert_blue_trans.png" %>
      </div>

      <div id="make_appointment" class="sidebar-item shadowed">
        <!-- TODO: Use the database for this. -->
        <h2>Specials</h2>
          <p>A/C Service With Freon (Most Cars): <b>$80</b></p>
          <!-- <p>No specials at the moment.</p> -->
      </div>

    </div>
  </div>

  <%= render 'home/footer' %>
</body>

</html>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation" class="appointment errors">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="appointment form-wrap">
    <div class="appointment form">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="appointment form">
      <%= f.label :text %><br>
      <%= f.text_area :text, size: "50x10" %>
    </div>
    <div class="appointment form">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<div id="wrapper">
  <h1>Editing review</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @review %> |
  <%= link_to 'Back', "/home/reviews" %>
</div>

app/views/reviews/index.html.erb
<div class="main-item shadowed">
  <h1>Customer Reviews</h1>
</div>

<% if @reviews.empty? %>
<div class="main-item shadowed">
  <p>There are currently no reviews posted. Check back later.</p>
</div>
<% end %>

<% @reviews.each do |review| %>
<div class="main-item shadowed">
  <figure>
    <figcaption>
      <%= review.name %> says...
    </figcaption>

    <blockquote>
      <q><i><%= review.text %></i></q>
    </blockquote>

  </figure>
</div>
<% end %>

<!-- <br> -->
<%# <%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<div id="wrapper">
  <h1>New review</h1>

  <%= render 'form' %>

  <%= link_to 'Back', reviews_path %>
</div>

app/views/reviews/show.html.erb
<div id="wrapper">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @review.name %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= @review.text %>
  </p>

  <%= link_to 'Edit', edit_review_path(@review) %> |
  <%= link_to 'Back', reviews_path %>
</div>